/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Test");
        return true;
    }

    public static void main(String[] args) {
        System.out.println(new Library().someLibraryMethod());
    }


}
